### ISSUE TITLE
bower install missing from instructions

### ISSUE THREAD

**Issue by lukemcd** [archfirst/angular-template#1]
QuickStart instructions should be modified to include bower install:

$ npm install
**$ bower install**
$ gulp serve-dev

**Comment by nareshbhatia** [comment]
`npm install` automatically calls `bower install` (see [here](https://github.com/archfirst/angular-template/blob/master/package.json#L14)). So you don't need to call `bower install` explicitly.

Let me know if you are facing any issues with this.

**Comment by lukemcd** [comment]
ok, I see issue, on npm install I am getting:
`npm WARN cannot run in wd angular-template@0.1.0 bower install (wd=/Users/luke/Documents/lab_root/angular-template-master)`

Local issue I will look into.
