### ISSUE TITLE
VM16388:1 Uncaught ReferenceError: function is not defined

### ISSUE THREAD

**Issue by PratibhaP** [archfirst/angular-template#2]
This the snippet from html code which has only a button:-

    <button ng-click="onCreateClick()">Create</button>

Following is the directive and controller for the module:

    (function() {

    'use strict';

    angular.module('app.dashboard')
        .directive('tmplDashboard', directiveFunction)
        .controller('DashboardController', ControllerFunction);

    // ----- directiveFunction -----
    directiveFunction.$inject = [];

    /* @ngInject */
    function directiveFunction() {

        var directive = {
            restrict: 'E',
            templateUrl: 'components/dashboard/dashboard.html',
            scope: {},
            controller: 'DashboardController',
            controllerAs: 'vm'
        };

        return directive;
    }

    // ----- ControllerFunction -----
    ControllerFunction.$inject = ['$scope'];

    /* @ngInject */
    function ControllerFunction($scope) {

  
        $scope.onCreateClick() {
            console.log('Activated Dashboard View');
        }
    }

    })();

Function gets executed and logs the message, but getting following error,

**VM16519:1 Uncaught ReferenceError: onCreateClick is not defined.**

  [1]: https://github.com/archfirst/angular-template

Please let me know, where I am going wrong, and why the above error is occurring

**Comment by gowthambalashanmugam** [comment]
$scope.onCreateClick = function() {
        console.log('Activated Dashboard View');
    }
The function notation you coded is wrong. Use the above one instead

**Comment by PratibhaP** [comment]
I have updated the function notation.
I am using flatkit ui theme, they added following event,
$(document).on('click', '[ng-click]', function(e) {});
becuase of this error was occuring.
Thank you.
