### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

### ISSUE THREAD

**Issue by phamyqb** [archfirst/angular-template#5]
After i clone your application and run npm install => show me this error and somethings like this: 
 Can't find Python executable "python", you can set the PYTHON env variable.
Error: not found: python2

**Comment by nareshbhatia** [comment]
@phamyqb, unfortunately this template is too old (Angular 1) and is no longer supported.

**Comment by phamyqb** [comment]
@nareshbhatia yeah, thanks
